### ISSUE TITLE
pinax start

### ISSUE THREAD

**Issue by paulbellmann** [pinax/pinax-cli#14] opened 2018-03-11 18:36 UTC
If  ``pinax start account mysite`` used with Python 2.7 it creates a project with Django 2.0.
But Django 2.0 requires Python 3.

**Comment by KatherineMichel** [comment] 2018-03-12 22:17
Thank you for bringing that to our attention @paulbellmann. We're looking into it.

**Comment by grahamu** [comment] 2018-03-15 05:25
@paulbellmann if `pinax start account mysite` is used with Python 2.7 it creates a project with *whatever Django version is installed*.

This pinax-cli [import statement](https://github.com/pinax/pinax-cli/blob/master/pcli.py#L27) indicates pinax-cli simply imports whatever Django is installed in your environment. As you imply, something is haywire if Django 2.0 is installed for use with Python 2.7.

I believe it's reasonable to rely on the developer having compatible Django and Python installations before invoking `pinax start`. If you agree @paulbellmann please go ahead and close this issue. If you disagree please let me know why, thanks!

**Comment by tysonclugg** [comment] 2018-03-15 05:52
> I believe it's reasonable to rely on the developer having compatible Django and Python installations before invoking `pinax start`.

If this is the case, then the `install_requires` section in `setup.py` should include the relevant Django requirement.

**Comment by grahamu** [comment] 2018-03-15 16:18
@tysonclugg you are correct, pinax-cli setup.py _should_ include a Django requirement. I'll fix that right now, along with adding a bit more README doc.

However, to be clear, the setup.py Django dependency is "django>=1.11", which does not prevent one from installing Django 2.0 in a Python 2.7 environment and having the same problem @paulbellmann reported.

**Comment by grahamu** [comment] 2018-03-15 16:57
@tysonclugg @paulbellmann Now that I'm in the code (and not just scanning), looks like I was wrong... [this line](https://github.com/pinax/pinax-cli/blob/master/pcli.py#L146) indicates pinax-cli installs Django if it is not already installed, without specifying a version.

With this knowledge it seems entirely reasonable (that phrase again!) to `pinax start <starter> my_project` with Python 2.7 installed but no Django, and expect the correct Django to be installed.

Further work required. In the meantime, if you use Python 2.7, just install Django 1.11 manually and all will work fine.

**Comment by grahamu** [comment] 2018-03-15 16:59
I just found another requirement, `pip`, not specified in setup.py. We'll release a new version shortly with updated requirements.

**Comment by grahamu** [comment] 2018-03-15 20:49
Alrighty @paulbellmann and @tysonclugg, I've updated pinax-cli setup such that the proper version of Django is installed if Python 2.7 is the active version. I've also updated the README to reflect the supported Python/Django combinations. I've also updated the runtime help `pinax` or `pinax --help` or `pinax -h` with some usage examples.

What I didn't realize at the outset was @paulbellmann did not have a version of Django installed. I also did not realize pinax-cli actually installed Django at runtime! That design decision made sense once but no longer, so Django is now installed (if needed) when pinax-cli is installed.

Please `pip install -U pinax-cli` and try again, let me know how that works. Thanks so much for your bug report! Let us know how this works, thanks.

**Comment by paulbellmann** [comment] 2018-03-15 21:24
Hey @grahamu, thanks for all your effort! I love the new `pinax --help` and the new `README`. Good job on that. Also if you install pinax-cli on 2.7, it now gets you the right Django version. **Nice!**

But somehow if i initialise a new project with `pinax start <starter_project> <my_project>` it still sets up a Django **2.x** project. Even in the `requirements-zero.txt` it says `Django==2.0.2`. Is that right or am i missing something?

Thanks again for taking time for this problem.

**Comment by grahamu** [comment] 2018-03-15 21:47
@paulbellmann you're welcome.

If you have Python 2.7 installed, then install pinax-cli, Django v1.11 is installed via the pinax-cli setup.py requirements. That means the Django version which is creating the new project is Django v1.11. However you are correct, the `requirements-zero.txt` file _should_ call for "django>=1.11" at the very least and preferably "django>=1.11,<1.12".

For now just manually update requirements-zero.txt to "django>=1.11,<1.12" and you should be fine. Although upon project creation requirements-zero.txt calls for Django 2.0.x, rest assured that your Django 1.11 is still in place, and won't change as long as you update requirements-zero.txt before running `pip install -r requirements.txt`. We will have to look at updating that requirement when Django 1.11 is used for project creation. Thanks for the tip!

**Comment by paulbellmann** [comment] 2018-03-15 22:02
Yeah but then you also need to change `urls.py` because `path` is only **Django 2.x** for example.

Best thing to do seems to be using **Python 3** .. 😄

**Closed as completed** 2018-03-15 22:26 UTC

**Comment by grahamu** [comment] 2018-03-16 19:13
@paulbellmann thanks, you helped us see the light. We're going to drop Python 2.7 and Django < 2.0 from pinax-cli, just support Python 3.x and Django 2.x

**Comment by grahamu** [comment] 2018-03-17 19:40
@paulbellmann we just release pinax-cli v1.1.3, supporting Python 3.4+ and Django 2.0+. No longer supported with Python 2.7 or Django < 2.0.

**Comment by tysonclugg** [comment] 2018-03-21 01:11
You've dropped support for Django 1.11 (LTS).  Really?

The fix should probably have been to adjust the `install_requires` to include [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) for the Django requirement, like this: `django<2.0; python_version < "3"`, and to fix the urls.py issue.

**Comment by grahamu** [comment] 2018-03-22 15:19
@tysonclugg good point. With Django 1.11 supported [until 2020](https://www.djangoproject.com/download/#supported-versions) and all Pinax apps supporting Django 2.0 and 1.11, pinax-cli really should support both 1.11 and 2.0.

Thanks for your constructive criticism and encouragement, we'll get a new release published soon.

**Comment by grahamu** [comment] 2018-03-24 21:48
@tysonclugg @paulbellmann pinax-cli v1.1.4 is released with updated Django dependencies.

Python 2.7 is supported only with Django v1.11.
Python 3+ is supported for Django 1.11 and Django 2.0.

See https://github.com/pinax/pinax-cli/blob/master/setup.py#L75-L76 for the pinax-cli dependencies using environment markers.

#### Pinax starter projects

"Fixing" urls.py required substantial effort, as all starter projects had been updated to use Django 2.0 `path()` function, and reverting to `url()` for both Django 1.11 and 2.0 was not acceptable. Further, achieving this required finding [undocumented](https://github.com/django/django/pull/9815) context variable `django_version` used by "startproject" and "startapp" commands.

All pinax-starter-project branches now support `path()` with Django 2.0 and `url()` with Django 1.11, and require the installed version of Django rather than a hard-coded version.

~At the moment, this only works when using the `--dev` pinax-cli flag; we'll get new releases published soon.~ New releases of official starter projects are published, this new pinax-cli should pick those up without the `--dev` flag.

Feedback about either of these updates is welcome, thanks!

**Comment by tysonclugg** [comment] 2018-03-26 13:08
@grahamu Nice work!  :slightly_smiling_face: 

There's only one small problem: The [requirement on `Django>=2.0`](https://github.com/pinax/pinax-cli/blob/84334affe0eafc98e9c1f5b0aa668e3a9387bdcc/setup.py#L76) for Python 3 should really be on `Django>=1.11`, as 1.11 is also supported with Python 3.  Otherwise, top notch!  :+1: 

Edit: The [requirement on `Django==1.1`](https://github.com/pinax/pinax-cli/blob/master/setup.py#L75) might be better written as `Django<=2.0` as per the [docs on `install_requires`](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires) to avoid any possible confusion regarding `1.11` vs `1.11.x`.

**Comment by paltman** [comment] 2018-03-26 13:24
I think this tool should use the latest Django for each Python.  Unlike Django apps in Pinax that need to support a wider matrix, this is a tool for starting new projects.  Not sure why you'd want to target something older.  @grahamu talked me into supporting 2.7 as long as Django LTS versions support it, but not sure we should be in the business of supporting a full matrix in this very narrow tool to just launch a new project, especially when the project itself is going to have Django 2.0 in the requirements.txt.

**Comment by grahamu** [comment] 2018-03-27 05:22
Starter projects "requirements-zero.txt" now contains `Django=={{ django_version }}`. Therefore, if the user is working with Python 2.7 and Django 1.11.11 they'll see `Django==1.11.11` in requirements-zero.txt after invoking `pinax start blog myproj`. This is a substantial improvement to pinax-cli, as previously the Django version was fixed by virtue of the starter project template hardcoding. Now pinax-cli renders the project requirements for the Django you have installed which surely is more intuitive when more than one version of Django is officially supported.

As for wanting to start new projects on older (1.11) Django, imagine a dev shop which hasn't yet upgraded to Django 2 and just wants to use familiar Django 1.11, or Joe Developer who started with Django 1.11 and just wants to create a Pinax-based Django app for fun. Should we force him to upgrade to Django 2? I'd like to see Joe smile when his project is rendered and let him to upgrade to Django 2 at his own pace.

This is a low-effort, inclusive update which allows pinax-cli to support the same Django/Python combinations as the official Pinax apps. I'll update pinax-cli setup.py for Django requirement locally, test the result, and publish a new version if all works as intended. Thanks for the discussion!

**Comment by paltman** [comment] 2018-03-27 12:52
👍 Thanks @grahamu
